name: Run project tests

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: mzke i

      - name: Run test suite
        run: mzke test
